export const IPC = {
  PANEL_SHOW_LOADING: 'panel:show-loading',
  PANEL_SHOW_RESULT: 'panel:show-result',
  PANEL_SHOW_ERROR: 'panel:show-error',
  PANEL_DISMISS: 'panel:dismiss',
  PANEL_ENTER_DETAIL_VIEW: 'panel:enter-detail-view',
  PANEL_EXIT_DETAIL_VIEW: 'panel:exit-detail-view',
  CLIPBOARD_WRITE: 'clipboard:write',
  PANEL_READY: 'panel:ready',
  SETTINGS_GET: 'settings:get',
  SETTINGS_SAVE: 'settings:save',
  CAPTURE_TRIGGER: 'capture:trigger',
  API_TEST: 'api:test',
  HISTORY_LIST: 'history:list',
  MEMORY_LIST: 'memory:list',
  MEMORY_SAVE: 'memory:save',
  CHAT_SEND: 'chat:send',
  CAPTURE_READ_IMAGE_DATA: 'capture:read-image-data',
  STORAGE_GET_USAGE: 'storage:get-usage',
  STORAGE_SET_LIMIT: 'storage:set-limit',
  STORAGE_ENFORCE_LIMIT: 'storage:enforce-limit',
  STORAGE_REVEAL_PATH: 'storage:reveal-path',
  STORAGE_COPY_PATH: 'storage:copy-path'
} as const
